# Generated by Django 2.1.7 on 2019-04-05 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho', models.IntegerField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=300)),
                ('documento_privado', models.BooleanField(default=False)),
                ('pessoa_dono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_doc_dono', to='GED.Pessoa')),
                ('pessoa_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_doc_usuario', to='GED.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Documento_Visibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibilidade', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GED.Documento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GED.Pessoa')),
            ],
        ),
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
        migrations.AddField(
            model_name='anexo',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GED.Documento'),
        ),
    ]
