# Generated by Django 2.1.7 on 2019-04-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0004_auto_20190405_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexo',
            old_name='url',
            new_name='arquivo',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='url',
            new_name='arquivo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tamanho',
        ),
    ]
