# Generated by Django 2.2 on 2019-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0005_auto_20190405_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento_visibilidade',
            name='visibilidade',
            field=models.BooleanField(default=True, verbose_name='Visivel'),
        ),
    ]
