# Generated by Django 2.2 on 2019-04-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0006_auto_20190422_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
