# Generated by Django 2.2 on 2019-05-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0009_auto_20190505_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='thumb',
            field=models.ImageField(editable=False, null=True, upload_to='uploads/thumbnail'),
        ),
    ]
