# Generated by Django 2.1.7 on 2019-05-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0009_auto_20190505_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
