# Generated by Django 2.2 on 2019-05-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0010_documento_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='thumb',
            field=models.ImageField(editable=False, null=True, upload_to='uploads/'),
        ),
    ]
