# Generated by Django 2.2 on 2019-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0010_auto_20190512_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='arquivo',
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
