# Generated by Django 2.2 on 2019-05-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0011_auto_20190507_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='arquivo',
            new_name='upload',
        ),
    ]
