# Generated by Django 2.2 on 2019-05-13 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GED', '0013_auto_20190513_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexo',
            old_name='file_upload',
            new_name='arquivo',
        ),
        migrations.RemoveField(
            model_name='documento_visibilidade',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='documento_visibilidade',
            name='visibilidade',
        ),
        migrations.AddField(
            model_name='documento_visibilidade',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
