# Generated by Django 2.2 on 2019-05-13 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GED', '0014_auto_20190513_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='compartilhamento',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
