# Generated by Django 2.2 on 2019-05-13 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GED', '0015_documento_compartilhamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='compartilhamento',
        ),
        migrations.AddField(
            model_name='documento',
            name='compartilhamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='documento_visibilidade',
            name='usuario',
        ),
        migrations.AddField(
            model_name='documento_visibilidade',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
