# Generated by Django 2.2 on 2019-05-13 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GED', '0016_auto_20190513_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento_visibilidade',
            name='usuario',
        ),
        migrations.AddField(
            model_name='documento_visibilidade',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
