# Generated by Django 2.2 on 2019-05-13 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GED', '0017_auto_20190513_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='compartilhamento',
        ),
        migrations.RemoveField(
            model_name='documento_visibilidade',
            name='usuario',
        ),
        migrations.AddField(
            model_name='documento',
            name='pessoa_compartilha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Compartihar'),
        ),
        migrations.AddField(
            model_name='documento_visibilidade',
            name='pessoa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='GED.Pessoa'),
        ),
        migrations.AddField(
            model_name='documento_visibilidade',
            name='visibilidade',
            field=models.BooleanField(default=True, verbose_name='Visivel'),
        ),
        migrations.AlterField(
            model_name='documento_visibilidade',
            name='documento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='GED.Documento'),
        ),
    ]
