# Generated by Django 2.2 on 2019-05-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0018_auto_20190513_1515'),
        ('GED', '0012_auto_20190508_0034'),
    ]

    operations = [
    ]
