# Generated by Django 2.2 on 2019-05-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0019_merge_20190513_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='upload',
            new_name='arquivo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='thumb',
        ),
    ]
