# Generated by Django 2.2 on 2019-05-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0020_auto_20190513_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento_visibilidade',
            name='visibilidade',
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
