# Generated by Django 2.2 on 2019-05-14 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GED', '0022_auto_20190514_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento_visibilidade',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='documento_visibilidade',
            name='destinatario',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
