# Generated by Django 2.2 on 2019-05-14 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0023_auto_20190514_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pessoa_compartilha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compartihar'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='pessoa_dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_doc_dono', to='GED.Pessoa', verbose_name='Referente a'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='pessoa_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_doc_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
