# Generated by Django 2.2 on 2019-05-15 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GED', '0024_auto_20190514_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento_visibilidade',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='documento_visibilidade',
            name='destinatario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
