# Generated by Django 2.2 on 2019-05-17 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GED', '0025_auto_20190515_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pessoa_compartilha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Pessoa', verbose_name='Compartihar'),
        ),
        migrations.RemoveField(
            model_name='documento_visibilidade',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='documento_visibilidade',
            name='destinatario',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
