# Generated by Django 2.2 on 2019-05-17 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0026_auto_20190517_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pessoa_compartilha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compartihar'),
        ),
    ]
