# Generated by Django 2.2 on 2019-05-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0027_auto_20190517_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GED.Documento'),
        ),
    ]
