# Generated by Django 2.2 on 2019-05-17 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GED', '0028_auto_20190517_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compartihar'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='pessoa_compartilha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Pessoa', verbose_name='Compartihar'),
        ),
    ]
