# Generated by Django 2.2 on 2019-05-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0029_auto_20190517_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Compartihar'),
        ),
    ]
